### ISSUE TITLE
After Symbol Rest to 2.3.6 upgrade, caught error 503 connection failed is appeared.

### ISSUE THREAD

**Issue by hitobb** [symbol/symbol-bootstrap#269]
**Describe the bug**

After Symbol Rest to 2.3.6 upgrade, caught error 503 connection failed is appeared.
And I can not sync with newest blockchain.  

```node            | Waiting for broker to start
node            | Waiting for broker to start
node            | Waiting for broker to start
node            | Waiting for broker to start
rest-gateway    | verbose: connecting to node:7900 {"timestamp":"2021-06-19T13:07:56.536Z"}
rest-gateway    | verbose: error raised by node:7900 connection:  connect ECONNREFUSED 172.20.0.4:7900 {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"172.20.0.4","port":7900,"stack":"Error: connect ECONNREFUSED 172.20.0.4:7900\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)","timestamp":"2021-06-19T13:07:56.538Z"}
rest-gateway    | error: caught error 503 connection failed {"jse_shortmsg":"connection failed","jse_info":{},"body":{"code":"ServiceUnavailable","message":"connection failed"},"stack":"ServiceUnavailableError: connection failed\n    at Object.createServiceUnavailableError (/app/catapult-rest/rest/_build/server/errors.js:56:44)\n    at TLSSocket.<anonymous> (/app/catapult-rest/rest/_build/connection/connectionService.js:104:20)\n    at TLSSocket.emit (events.js:327:22)\n    at net.js:674:12\n    at TCP.done (_tls_wrap.js:567:7)","timestamp":"2021-06-19T13:07:56.538Z"}
node            | Waiting for broker to start
node            | Waiting for broker to start
node            | Waiting for broker to start

```
The above behavior loops.

**To Reproduce**
To reproduce the behavior:

1. First, I'm update only bootstrap to 1.0.6

```
symbol-bootstrap/1.0.6 linux-x64 node-v14.17.1
```

The node is working normally at this timing

2.Next,I'm upgrade other components.

```
symbol-bootstrap config -p mainnet -a dual --upgrade
symbol-bootstrap compose --upgrade
```

3. The issue has occurred.

**Expected behavior**

Fix the error 503 connection failed to work fine. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Tool Version : symbol-bootstrap/1.0.6 linux-x64 node-v14.17.1
 - Docker Version:Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2
 - Node Version:node-v14.17.1

**Comment by fboucquez** [comment]
This issue is related to rest not being able to talk to catapult. Do you have the logs? catapult server/broker may not have fully loaded

**Comment by hitobb** [comment]
Thank you for checking.

I will attach my operation log.
Do you have any other logs you need? 
This issue is easy to reproduce in my environment, so any log can be provided.

[script_170447.log](https://github.com/symbol/symbol-bootstrap/files/6839144/script_170447.log)

**Comment by Wayonb** [comment]
@hitobb Thanks for the logs.  
The logs shows there is an issue with the harvester file.  Was this modify or did you change your keys?  It seems like the decrypt of the harvester was unsuccessful.  
I cant tell what happened before since the uploaded logs dont have that information.

````
[32mnode            |[0m [31m2021-07-19 08:07:34.486010 0x00007fb8d7fffac0: <error> (src::UnlockedAccountsStorage.cpp@160) Throwing exception: malformed harvesters file [0m
[32mnode            |[0m 2021-07-19 08:07:34.501134 0x00007fb8d7fffac0: <info> (utils::StackLogger.h@43) popping scope 'booting local node' (233ms) [0m
[32mnode            |[0m [31m2021-07-19 08:07:34.501169 0x00007fb8d7fffac0: <fatal> (local::HostUtils.h@43) unhandled exception while boot!
[32mnode            |[0m /catapult-src/extensions/harvesting/src/UnlockedAccountsStorage.cpp(160): Throw in function void catapult::harvesting::UnlockedAccountsStorage::load(const KeyPair&, catapult::consumer<catapult::harvesting::BlockGeneratorAccountDescriptor&&>&)
[32mnode            |[0m Dynamic exception type: boost::wrapexcept<catapult::catapult_error<std::runtime_error> >
[32mnode            |[0m std::exception::what: malformed harvesters file
[32mnode            |[0m  [0m
[32mnode            |[0m [31m2021-07-19 08:07:34.501232 0x00007fb8d7fffac0: <error> (local::HostUtils.h@44) Throwing exception: malformed harvesters file [0m
[32mnode            |[0m [31m2021-07-19 08:07:34.501401 0x00007fb8d7fffac0: <fatal> (process::ProcessMain.cpp@75)
[32mnode            |[0m thread: server catapult
[32mnode            |[0m unhandled exception while running local node!
[32mnode            |[0m /catapult-src/src/catapult/local/HostUtils.h(44): Throw in function std::unique_ptr<_Tp> catapult::local::CreateAndBootHost(TArgs&& ...) [with THost = catapult::local::{anonymous}::DefaultLocalNode; TArgs = {std::unique_ptr<catapult::extensions::ProcessBootstrapper, std::default_delete<catapult::extensions::ProcessBootstrapper> >, const catapult::config::CatapultKeys&}]
[32mnode            |[0m Dynamic exception type: boost::wrapexcept<catapult::catapult_error<std::runtime_error> >
[32mnode            |[0m std::exception::what: malformed harvesters file
````

**Comment by hitobb** [comment]
Sorry for the late report.

I couldn't find the cause of how the harvester file got corrupted.
So,Today I’m working the new install using boot-strap 1.0.7.
And I avoided this issue by manually registering all the settings.

I will close this issue.
Thank you.
