### ISSUE TITLE
Cannot connect node from rest-gateway

### ISSUE THREAD

**Issue by koma2crew** [symbol/symbol-bootstrap#319]
**Describe the bug**
I started symbol-bootstrap, but healthCheck is not OK. When I check the log, the connection from the rest-gateway to the node is in error. Is there a way to solve this?

**To Reproduce**
To reproduce the behavior:
1. `symbol-bootstrap start -p mainnet -a dual -c default-preset.yml --upgrade -d`

**Logs**

Run healthCheck of symbol-bootstrap
```
$ symbol-bootstrap healthCheck
                         _             _         _                    _         _
  ___  _   _  _ __ ___  | |__    ___  | |       | |__    ___    ___  | |_  ___ | |_  _ __  __ _  _ __
 / __|| | | || '_ ` _ \ | '_ \  / _ \ | | _____ | '_ \  / _ \  / _ \ | __|/ __|| __|| '__|/ _` || '_ \
 \__ \| |_| || | | | | || |_) || (_) || ||_____|| |_) || (_) || (_) || |_ \__ \| |_ | |  | (_| || |_) |
 |___/ \__, ||_| |_| |_||_.__/  \___/ |_|       |_.__/  \___/  \___/  \__||___/ \__||_|   \__,_|| .__/
       |___/                                                                                    |_|
2021-11-14T12:40:41.009Z info     Container db is running
2021-11-14T12:40:41.011Z info     Container node is running
2021-11-14T12:40:41.014Z info     Container broker is running
2021-11-14T12:40:41.014Z info     Container rest-gateway is running
2021-11-14T12:40:41.016Z info     Container node port 7900 -> 7900 is open
2021-11-14T12:40:41.017Z info     Container rest-gateway port 3000 -> 3000 is open
2021-11-14T12:40:41.018Z info     Testing http://localhost:3000/node/health
2021-11-14T12:40:41.076Z warn     Rest http://localhost:3000/node/health is NOT up and running YET: {"statusCode":503,"statusMessage":"Service Unavailable","body":"{\"status\":{\"apiNode\":\"down\",\"db\":\"up\"}}"}
2021-11-14T12:40:41.076Z info     Retrying in 10 seconds. Polling will stop in 50.835 seconds
Unavailable","body":"{\"status\":{\"apiNode\":\"down\",\"db\":\"up\"}}"}
    Error: Network did NOT start!!!
```

docker error
```
$ cd target/docker
docker $ docker-compose logs -f rest-gateway
rest-gateway    | verbose: connecting to node:7900 {"timestamp":"2021-11-14T12:50:49.830Z"}
rest-gateway    | error: caught error 503 connection failed {"body":{"code":"ServiceUnavailable","message":"connection failed"},"jse_info":{},"jse_shortmsg":"connection failed","stack":"ServiceUnavailableError: connection failed\n    at Object.createServiceUnavailableError (/app/catapult-rest/rest/src/server/errors.js:56:44)\n    at TLSSocket.<anonymous> (/app/catapult-rest/rest/src/connection/catapultConnection.js:27:53)\n    at Object.onceWrapper (events.js:421:26)\n    at TLSSocket.emit (events.js:326:22)\n    at net.js:675:12\n    at TCP.done (_tls_wrap.js:568:7)","timestamp":"2021-11-14T12:50:49.841Z"}
```

**Desktop (please complete the following information):**
 - OS: CentOS 7.9
 - Tool Version：symbol-bootstrap/1.1.0 linux-x64 node-v12.22.6
 - Docker Version：Docker version 20.10.5, build 55c4c88
 - Node Version：v12.22.6

**Comment by fboucquez** [comment]
It seems like the catapult client did not run correctly and Rest cannot connect to it. Rest is ok, just the client is down. Do you have catapult logs?
